name: Push commit

on: push

jobs:
  report:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ linux, macos, windows ]
        include:
          - build: linux
            os: ubuntu-latest
            name: linux
          - build: macos
            os: macos-latest
            name: macos
          - build: windows
            os: windows-latest
            name: windows
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: check if commit is auto
        id: check
        continue-on-error: true
        run: |
          if git log -1 --pretty=%B | grep -q "\[auto\]"; then
            echo "auto commit"
            exit 1
          else
            echo "manual commit"
            exit 0
          fi

      - uses: actions/setup-node@v4
        if: steps.check.outcome == 'success'
        with:
          node-version: '22'

      - name: Install pnpm
        if: steps.check.outcome == 'success'
        run: npm install -g pnpm

      - name: Install dependencies
        if: steps.check.outcome == 'success'
        run: |
          cp -r ./app ./build/${{ matrix.name }}
          cd ./build/${{ matrix.name }}/app
          pnpm install
          rm .gitignore

      - name: Commit
        if: steps.check.outcome == 'success'
        run: |
          git config --global user.name 'Jaeyong Sung'
          git config --global user.email 'buttercrab@users.noreply.github.com'
          git add .
          git commit -m "[auto] build node_modules" . > /dev/null 2> /dev/null
          while true; do
            git pull
            git push
            [ $? -eq 0 ] && break
            sleep 1
          done
