name: Push commit

on: push

jobs:
  report:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ linux, macos, windows ]
        include:
          - build: linux
            os: ubuntu-latest
            name: linux
          - build: macos
            os: macos-latest
            name: macos
          - build: windows
            os: windows-latest
            name: windows
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: check if commit is auto
        id: check
        continue-on-error: true
        run: |
          (git log -1 --pretty=%B | grep -q "\[auto\]") && exit 1 || exit 0

      - uses: actions/setup-node@v2
        if: steps.check.outcome == 'success'
        with:
          node-version: '22'

      - name: Install pnpm
        if: steps.check.outcome == 'success'
        run: npm install -g pnpm
        working-directory: ./build/${{ matrix.name }}/app

      - name: Install dependencies
        if: steps.check.outcome == 'success'
        run: pnpm install
        working-directory: ./build/${{ matrix.name }}/app

      - name: move node_modules
        if: steps.check.outcome == 'success'
        run: mv ./build/${{ matrix.name }}/app/node_modules ./build/${{ matrix.name }}/node_modules

      - name: Commit
        if: steps.check.outcome == 'success'
        run: |
          git config --global user.name 'Jaeyong Sung'
          git config --global user.email 'buttercrab@users.noreply.github.com'
          git add . > /dev/null 2> /dev/null
          git commit -am "[auto] build node_modules"
          git push
