name: Push commit

on: push

jobs:
  report:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ linux, macos, windows ]
        include:
          - build: linux
            os: ubuntu-latest
            name: linux
            check: |
              if git log -1 --pretty=%B | grep -q "\[auto\]"; then
                echo "auto commit"
                exit 1
              else
                echo "manual commit"
                exit 0
              fi
            script: ./action-linux.sh

          - build: macos
            os: macos-latest
            name: macos
            check: |
              if git log -1 --pretty=%B | grep -q "\[auto\]"; then
                echo "auto commit"
                exit 1
              else
                echo "manual commit"
                exit 0
              fi
            script: ./action-macos.sh

          - build: windows
            os: windows-latest
            name: windows
            check: |
              if (git log -1 --pretty=%B | Select-String -Pattern "\[auto\]") {
                echo "auto commit"
                exit 1
              } else {
                echo "manual commit"
                exit 0
              }
            script: ./action-windows.ps1
    steps:
      - run: git config --system core.longpaths true

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: check if commit is auto
        id: check
        continue-on-error: true
        run: ${{ matrix.check }}

      - uses: actions/setup-node@v4
        if: steps.check.outcome == 'success'
        with:
          node-version: '22'

      - name: Run script
        if: steps.check.outcome == 'success'
        run: ${{ matrix.script }}
